import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// Tiga sidebar terpisah, satu per kategori folder di docs/ (root repo).
// Masing-masing auto-generated dari struktur file, jadi menambah file baru
// di dalam foldernya otomatis muncul di sidebar tanpa perlu ubah file ini.
const sidebars: SidebarsConfig = {
  panduanPenggunaSidebar: [
    {
      type: 'autogenerated',
      dirName: 'panduan-pengguna',
    },
  ],
  panduanDeveloperSidebar: [
    {
      type: 'autogenerated',
      dirName: 'panduan-developer',
    },
  ],
  rekayasaOperasionalSidebar: [
    {
      type: 'autogenerated',
      dirName: 'rekayasa-operasional',
    },
  ],
};

export default sidebars;
